title: Liberty Security Foundation
email: hello@libertyinfosec.com
description: A short description of your site
baseurl: 'lib-sec-foundation'
url: 'libertyinfosec.com'
plugins:
  - jekyll-seo-tag
sass:
  sass_dir: assets/css
